import type { Metadata } from "next";
import { newsreader, poppins } from "./lib/fonts/fonts";
import "./globals.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${newsreader.variable} ${poppins.variable}`}
      suppressHydrationWarning
    >
      <body className={`${newsreader.className}`}>
        {children}
      </body>
    </html>
  );
}
